# Generated by Django 4.0.3 on 2022-04-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_image1_alter_review_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
